# Build settings
markdown: redcarpet
highlighter: rouge
gems:
  - jemoji
  - jekyll-paginate
  
# Site settings
title: "Sergio Pérez"
description: > # this means to ignore newlines until "email:"
   Blog de Sergio Pérez

email: seperezf@hotmail.com
#blog logo
logo: "http://www.gravatar.com/avatar/c09f96e3d69b0808392cd75a197e199bfs=600"
# blog cover
cover: "/assets/images/intel.jpg"

name: 'Sergio Pérez'
author: 'Sergio Pérez'
author_image: "http://www.gravatar.com/avatar/c09f96e3d69b0808392cd75a197e199bfs=300"

paginate:	5

url: "http://blog.seperez.com" # the base hostname & protocol for your site
baseurl: ""

# social icons and sharing options
social:

  - icon:	github
    url:	https://github.com/sergioperezf
    desc:	Github
    share_url:
    share_title:
    share_link:

  - icon:	stack-overflow
    url:	http://stackoverflow.com/users/1200802/chechopeefe?tab=profile
    desc:	Stack Overflow
    share_url:
    share_title:
    share_link:

  - icon:	globe
    url:	http://seperez.com
    desc:	Portfolio
    share_url:
    share_title:
    share_link:

  - icon:	linkedin
    url:	https://linkedin.com/in/sergio-perez-7a51173
    desc:	LinkedIn
    share_url:
    share_title:
    share_link:
